version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itm-main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - itmo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 6

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "9991:9991"
    networks:
      - itmo
    environment:
      CONFIG_REPO_URI: https://github.com/ITMO-WORK/itmo-work-configs-repo-lab2 
      CONFIG_REPO_USERNAME: UserName
      CONFIG_REPO_PASSWORD: Password 
  
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_started
    networks:
      - itmo
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:9991
  

#  application-service:
#    build: ./application-service
#    container_name: application-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#      config-server:
#        condition: service_started
#      eureka-server:
#        condition: service_started
#    networks:
#      - itmo
#    environment:
#      SPRING_CONFIG_IMPORT: configserver:http://config-server:9991/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
#      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/application-db
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: postgres
#
#      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/application-db
#      LIQUIBASE_USER: postgres
#      LIQUIBASE_PASSWORD: postgres
#
#
#  company-service:
#    build: ./company-service
#    container_name: company-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#      config-server:
#        condition: service_started
#      eureka-server:
#        condition: service_started
#    networks:
#      - itmo
#    environment:
#      SPRING_CONFIG_IMPORT: configserver:http://config-server:9991/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
#      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/company-db
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: postgres
#
#      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/company-db
#      LIQUIBASE_USER: postgres
#      LIQUIBASE_PASSWORD: postgres
#
#
#
#  user-service:
#    build: ./user-service
#    container_name: user-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#      config-server:
#        condition: service_started
#      eureka-server:
#        condition: service_started
#    networks:
#      - itmo
#    environment:
#      SPRING_CONFIG_IMPORT: configserver:http://config-server:9991/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user-db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#
#  vacancy_service:
#    build: ./vacancy_service
#    container_name: vacancy-service
#    depends_on:
#      postgres:
#        condition: service_healthy
#      config-server:
#        condition: service_started
#      eureka-server:
#        condition: service_started
#    networks:
#      - itmo
#    environment:
#      SPRING_CONFIG_IMPORT: configserver:http://config-server:9991/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vacancy-db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#  itmo-work-gateway:
#    build: ./itmo-work-gateway
#    container_name: itmo-work-gateway
#    ports:
#      - "8765:8765"
#    depends_on:
#      config-server:
#        condition: service_started
#      eureka-server:
#        condition: service_started
#      application-service:
#        condition: service_started
#      company-service:
#        condition: service_started
#      user-service:
#        condition: service_started
#      vacancy_service:
#        condition: service_started
#    networks:
#      - itmo
#    environment:
#      SPRING_CONFIG_IMPORT: configserver:http://config-server:9991/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

networks:
  itmo:
    driver: bridge

volumes:
  postgres_data:


