server:
  port: ${PORT:8765}

spring:
  application:
    name: itmo-work-gateway

  profiles:
    active: ${PROFILE:dev}

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # ===== APPLICATION SERVICE =====
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/application/**

            - id: application-docs
              uri: lb://application-service
              predicates:
                - Path=/v3/api-docs/application
              filters:
                - RewritePath=/v3/api-docs/application,/v3/api-docs

            # ===== USER SERVICE =====
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/user/**

            - id: user-docs
              uri: lb://user-service
              predicates:
                - Path=/v3/api-docs/user
              filters:
                - RewritePath=/v3/api-docs/user,/v3/api-docs

            # ===== COMPANY SERVICE =====
            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/company/**

            - id: company-docs
              uri: lb://company-service
              predicates:
                - Path=/v3/api-docs/company
              filters:
                - RewritePath=/v3/api-docs/company,/v3/api-docs

            # ===== VACANCY SERVICE =====
            - id: vacancy-service
              uri: lb://vacancy-service
              predicates:
                - Path=/api/vacancies/**

            - id: vacancy-docs
              uri: lb://vacancy-service
              predicates:
                - Path=/v3/api-docs/vacancy
              filters:
                - RewritePath=/v3/api-docs/vacancy,/v3/api-docs


            # ---------- OPTIONAL REDIRECT ----------
            - id: swagger-ui-redirect
              uri: http://localhost:8765
              predicates:
                - Path=/swagger-ui.html

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    urls:
      - name: vacancy-service
        url: /v3/api-docs/vacancy
      - name: company-service
        url: /v3/api-docs/company
      - name: user-service
        url: /v3/api-docs/user
      - name: application-service
        url: /v3/api-docs/application